version: "3.8"

services:
  rev:
    image: nginx
    network_mode: "host"
    ports:
      - "443:443"
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
      - ${PATH_FULLCHAIN:?Environment variable PATH_FULLCHAIN is not set in neither your shell nor .env file!}:/etc/nginx/keys/fullchain.pem:ro
      - ${PATH_PRIVKEY:?Environment variable PATH_PRIVKEY is not set in neither your shell nor .env file!}:/etc/nginx/keys/privkey.pem:ro

  app:
    image: nextcloud
    restart: always
    ports:
      - "127.0.0.1:3040:80"
    depends_on:
      - db
    environment:
      - MYSQL_HOST=db
      - MYSQL_DATABASE=nextcloud
      - MYSQL_USER=nextcloud
      - MYSQL_PASSWORD=nextcloud
    volumes:
      - ${PATH_DATA:?Environment variable PATH_DATA is not set in neither your shell nor .env file!}:/var/www/html

  db:
    image: ghcr.io/linuxserver/mariadb
    restart: always
    command: mysqld --character-set-server=utf8 --collation-server=utf8_unicode_ci
    environment:
      - MYSQL_DATABASE=nextcloud
      - MYSQL_ROOT_PASSWORD=password
      - MYSQL_USER=nextcloud
      - MYSQL_PASSWORD=nextcloud
    expose:
      - "3306"
    volumes:
      - ${PATH_DB:?Environment variable PATH_DB is not set in neither your shell nor .env file!}:/var/lib/mysql
